### ISSUE TITLE
User can create an entry

### ISSUE THREAD

**Issue by leejaejoseph** [leejaejoseph/code-journal#1]
## 💰 Motivation

Coders will want to capture tidbits they pick up during their research.

## 📐 Plan

Create a responsive form that allows users to store an image URL with some notes about a specific topic.

## 🖼️ Wireframes

![user can create an entry mobile](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/wireframes/code-journal/figma/user-can-create-an-entry-mobile.png)
![user can create an entry desktop](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/wireframes/code-journal/figma/user-can-create-an-entry-desktop.png)

## ✅ Task List
- [x] Create the HTML for the form that creates a journal entry in the `data-view="entry-form"` element. This form needs to match the format shown in the example figma.
- [x] Complete the HTML form using the appropriate responsive layout classes.
  - [x] Write CSS for mobile devices first.
  - [x] Adjust styling to fluidly adapt to desktop.
- [x] Make all inputs of the journal entry form `required`.
- [x] Add an `'input'` event listener to the Photo URL input that sets the `src` attribute of the photo preview to the input's value when the user types or pastes in a new URL.
- [x] Add a `'submit'` event listener to the form element that:
  - [x] prevents the page from refreshing when the form is submitted.
  - [x] stores the form's input values in a new object.
  - [x] assigns an `entryId` property to the new object, taken from the `nextEntryId` property of the data model.
  - [x] increments the `nextEntryId` property of the data model so that if another entry is submitted later, it will receive a different `entryId`.
  - [x] adds the new object to the beginning of the data model's array of entries.
  - [x] resets the preview image's `src` attribute back to the placeholder image.
  - [x] resets the form.
- [x] In `data.js`, add a `'beforeunload'` event listener to the `window` object that serializes the data model as JSON and stores the JSON in `localStorage`.
- [x] At the bottom of `data.js`, include a conditional statement that:
  - [x] checks to see if there is a JSON data model stored in `localStorage`.
  - [x] if there is, parse it and assign it to the initial `data` variable so that the user can continue adding entries to the pre-existing data model.
- [x] Test the app by submitting some new entries and then reloading the page to confirm that:
  - [x] the data model is being saved to `localStorage` before each page reload.
  - [x] each new journal entry object is receiving an incrementing `entryId` property.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
