### ISSUE TITLE
User can edit an entry

### ISSUE THREAD

**Issue by leejaejoseph** [leejaejoseph/code-journal#3]
## 💰 Motivation

If a user makes a mistake when creating an entry or wants to add more notes to an entry, they should be able to edit it.

## 📐 Plan

Allow users to select an existing entry to edit and pre-populate its information into the form.

## 🖼️ Wireframes

![user can edit an entry mobile](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/wireframes/code-journal/figma/user-can-edit-an-entry-mobile.png)
![user can edit an entry desktop](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/wireframes/code-journal/figma/user-can-edit-an-entry-desktop.png)

## ✅ Task List

- [x] Update the `renderEntry` function to do the following:
  - [x] Add a FontAwesome pencil icon next to the title of each entry which matches the figma example.
  - [x] Add a `data-entry-id` attribute to the `li` that stores the `entryId` of the `entry` being rendered.
- [x] Add an event listener to the `ul` in the entries view which does the following when an entry's pencil icon is clicked:
  - [x] Use the `viewSwap` function to show the form.
  - [x] Find the entry object in the `data.entries` array whose id matches the `data-entry-id` attribute value of the clicked entry and assigns that entry’s object to the `data.editing` property.
  - [x] Pre-populate the entry form with the clicked entry's values from the object stored in the `data.editing` property.
  - [x] Updates the title of the entry-form view to `Edit Entry`
- [x] Update the entry form's submit handler to do the following:
  - [x] if data.editing is null:
    - [x] perform the standard functionality for a new entry
  - [x] if data.editing is not null:
    - [x] Assign the entry id value from `data.editing` to the new object with the updated form values.
    - [x] Replace the original object in the `data.entries` array for the edited entry with the new object with the edited data.
    - [x] Render a new DOM tree for the new object with the updated data, and replace the original `li` with the matching `data-entry-id` value with the new generated DOM tree.
    - [x] Update the title on the form to `New Entry`.
    - [x] Reset data.editing to `null`.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
