### ISSUE TITLE
User can delete an entry

### ISSUE THREAD

**Issue by leejaejoseph** [leejaejoseph/code-journal#4]
## 💰 Motivation

If a user decides that they no longer wish to keep an entry, they should be able to delete it.

## 📐 Plan

Allow users to delete an entry from its edit screen.

## 🖼️ Wireframes

![user can delete an entry mobile](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/wireframes/code-journal/figma/user-can-delete-an-entry-mobile.png)
![user can delete an entry desktop](https://lfz-static.s3-us-west-1.amazonaws.com/graphics/wireframes/code-journal/figma/user-can-delete-an-entry-desktop.png)

## ✅ Task List
- [x] Add a button to the entry form with the text **Delete Entry** which is only visible when an entry is currently being edited.
- [x] Show a confirmation modal when the user clicks **Delete Entry**
- [x] When the user clicks **Cancel**, hide the modal.
- [x] When the user clicks **Confirm**:
  - [x] remove the corresponding entry object from the data model's entry array.
  - [x] remove the entry's `li` element from the DOM.
  - [x] conditionally uses the `toggleNoEntries` function to show the no entries text if needed.
  - [x] hide the modal.
  - [x] swap to the Entries view.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.

**Comment by leejaejoseph** [comment]
![user-can-delete](https://user-images.githubusercontent.com/116613246/210294252-038315de-e7dc-42a4-975c-9d9bc5a95f17.gif)
